name: Manual build API example

on:
  pull_request:
    paths:
      - '.github/workflows/example-build.yml'
      - 'example/**'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  local-ci:
    name: Example app
    runs-on: ubuntu-20.04
    container: python:3.10.5-slim

    # Setup PostgreSQL
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: schemathesis-example
        # Wait until Postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Install dependencies
        run: pip install -r example/requirements.txt && pip install .

      # Starts the API in the background
      - name: Start API
        run: python example/main.py &

      # Runs positive Schemathesis tests
      - uses: schemathesis/action@v1.0.0
        continue-on-error: true
        with:
          # A local API schema location
          schema: 'http://localhost:5000/api/openapi.json'
          # Set your token from secrets
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}
          max-examples: '10'
